config/routes.rb
Demoday::Application.routes.draw do


  root :to => 'static_pages#index'
  match '/map', to: 'static_pages#map'

  resources :startups

  resources :angellist_follows, only: [:create] # POST /follows
  resources :email_contacts, only: [:create] # POST /emails

  # $.post('/follows', {}, function() {
  #   $('#form_id').text('s');
  # })

  # Pings
  # match '/follow', to: 'pings#follow'
  # match '/send_email', to: 'pings#send_email'

  # Angellist Oauth
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: 'sessions#failure'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  # Omniauth Identities registration
  resources :identities

  # Become an Admin
  match '/admin', to: 'admin#index'
  match '/become_admin', to: 'admin#become_admin'
  
end

app/models/angellist_follow.rb
class AngellistFollow < ActiveRecord::Base
  attr_accessible :startup_id, :user_id

  belongs_to :user
end

app/models/email_contact.rb
class EmailContact < ActiveRecord::Base
  attr_accessible :startup_id, :user_id

  belongs_to :user
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation

  validates :password, :presence => true, :on => :create
  validates :name, :presence => true
  validates :name, :uniqueness => true

  emailRegex = /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates :email, :format => { :with => emailRegex }
end

app/models/startup.rb
class Startup < ActiveRecord::Base
  attr_accessible :angellist_id, :bio, :ceo_name, :email, :name, :presentation_order, :ceo_angellist_id, :domain_url, :ceo_slug

  def img_url
    self.name.downcase + '.jpg'
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_token, :provider, :uid, :investor, :email, :bio, :linkedin, :twitter

  has_many :angellist_follows
  has_many :email_contacts

  def self.from_omniauth(auth)
    auth[:uid] = auth[:uid].to_s
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid.to_s
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.investor = auth.info.investor
      user.twitter = auth.info.twitter_url
      user.linkedin = auth.info.linkedin_url
      user.bio = auth.info.bio
      user.save!
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :signed_in?

  def index
  end

  def become_admin
    password = 'tsdemoday'
    if params[:password] == password
      current_user.update_attribute(:admin, true)
      redirect_to root_path
    else
      redirect_to admin_path, alert: 'Incorrect Password'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def oauth_token
    @oauth_token = session[:oauth_token]
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def angellist_user?
    current_user.provider == 'angellist'
  end
  helper_method :angellist_user?

  def following_startup? startup_id
    startup_id = startup_id
    current_user.angellist_follows.where({ startup_id: startup_id }).empty?
  end
  helper_method :following_startup?

  def sent_email? startup_id
    startup_id = startup_id
    current_user.email_contacts.where({ startup_id: startup_id }).empty?
  end
  helper_method :sent_email?

  protected

  def admin?
    current_user && current_user.admin
  end
  helper_method :admin?

  def authorize
    unless admin?
      redirect_to root_path
      false
    end
  end

  def signed_in?
    unless current_user
      redirect_to root_path
      false
    end
  end

end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env["omniauth.identity"] || Identity.new
  end
end

app/controllers/pings_controller.rb
class PingsController < ApplicationController

  def follow
    angellist_id = params[:angellist_id]

    require 'net/http'
    $angel_api = Net::HTTP.new("api.angel.co", 443)
    $angel_api.use_ssl = true

    request = Net::HTTP::Post.new("/1/follows")
    request.set_form_data({"access_token" => current_user.oauth_token, "type" => "startup", "id" => angellist_id})
    $angel_api.request(request)

    redirect_to root_path
  end

  def send_email
    @startup = Startup.find(params[:id])

    UserMailer.contact_confirmation(@startup, current_user).deliver
    UserMailer.startup_email(@startup, current_user).deliver

    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    session[:oauth_token] = user.oauth_token
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    session[:oauth_token] = nil
    redirect_to root_url
  end

  def failure
    redirect_to root_path, alert: "Authentication failed, please try again."
  end
end

=begin
raise env["omniauth.auth"].to_yaml
--- !ruby/hash:OmniAuth::AuthHash
provider: angellist
uid: 292385
info: !ruby/hash:OmniAuth::AuthHash::InfoHash
  name: Kevin Chang
  email: kevinjhc@gmail.com
  bio: HackStar @techstars, @SnackStars, @StartupInst Graduate
  blog_url: 
  online_bio_url: http://kevinjhc.com/boston
  twitter_url: http://twitter.com/#!/kevinjhc
  facebook_url: 
  linkedin_url: 
  follower_count: 0
  angellist_url: https://angel.co/kevinjhc
  image: https://angel.co/images/shared/nopic.png
  locations: []
  roles: []
credentials: !ruby/hash:OmniAuth::AuthHash
  token: b76c43350bc40653221230568ae0097c
  expires: false
extra: !ruby/hash:OmniAuth::AuthHash {}
=end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController

  before_filter :authorize, :except => [:follow, :send_email]

  # You can only access this page as an admin. Else it redirects you to root
  def index
    redirect_to root_path
  end

  def new
    @startup = Startup.new
  end

  def create
    @startup = Startup.new(params[:startup])
    @startup.save
    redirect_to startups_path
  end

  def edit
    @startup = Startup.find(params[:id])
  end

  def update
    @startup = Startup.find(params[:id])
    @startup.update_attributes(params[:startup])
    redirect_to startups_path
  end

  def destroy
    @startup = Startup.find(params[:id])
    @startup.destroy
    redirect_to startups_path
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/angellist_follows_helper.rb
module AngellistFollowsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_contacts_helper.rb
module EmailContactsHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/pings_helper.rb
module PingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/index.html.erb
<div class="row">

<% if alert %>
<div class="row">
  <div class="large-12 columns width-90">
    <div data-alert class="alert-box radius alert">
      <%= alert %>
      <a href="#" class="close">&times;</a>
    </div>
  </div>
</div>
<% end %>

  <%= form_tag :controller => "admin", :action => "become_admin" do %>

    <div class="large-4 small-centered columns text-center width-90">

      <%= label_tag 'Admin Password' %>
      <%= password_field_tag :password %>

      <%= submit_tag "Become Admin", class: "button radius alert" %><br />
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="row">

  <div class="dot-border"></div>

  <div class="footer text-center">

    <% if current_user %>
      <p class="welcome">Hello, <strong><%= current_user.name %></strong>!</p>
      <%= link_to "Sign out?", signout_path, class: "button radius alert" %>
    <% else %>
      <%= render 'layouts/login_form' unless(params[:controller] == 'identities' && params[:action] == 'new')%>
    <% end %>

  </div>
  
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <a href="/"><div id="logo"></div></a>

  <!--
    <div class="nav">
      <a href="/"><i class="icon-users-1"></i></a>
      <a href="/map"><i class="icon-map"></i></a>
    </div>
  -->

</div>

<div class="triangle"></div>

app/views/layouts/_login_form.html.erb
<%= link_to "Sign in with Angellist", "/auth/angellist", class: "button radius alert angellist" %>

<h6 class="or">OR</h6>

<div id="email-login">
  <!--<%= submit_tag "Login via email", class: "button radius alert email-button" %>-->
  <%= link_to "Login via email", "#", :class => "button radius alert email-button" %>

  <%= form_tag "/auth/identity/callback", class: "email-form" do %>

    <div class="large-4 small-centered columns width-90">
      <%= label_tag :auth_key, "Email" %>
      <%= text_field_tag :auth_key %>

      <%= label_tag :password, "Password" %>
      <%= password_field_tag :password %>

      <!--<%= submit_tag "Login", class: "button radius alert" %>-->
      <%= button_to "Login", "/auth/identity/callback", :class => "button radius alert", :method => :get %>
    </div>

  <% end %>

  <br />
  <%= link_to "Create an account?", new_identity_path, class: 'create-account' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <%= favicon_link_tag 'favicon.ico' %>

  	<title><%= content_for?(:title) ? yield(:title) : "Demo Day Buddy" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<!--<%= javascript_include_tag "vendor/custom.modernizr" %>-->
    <%= csrf_meta_tags %>
  </head>

  <body>



  <%= render 'layouts/header' %>

  <div id="content">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <%= javascript_include_tag "application" %>

  </body>
</html>